name: Build

on:
  push:
    branches: main
    
concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: setup python to build package
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install build
        run: python -m pip install build
      - uses: actions/checkout@v4
      - name: build package
        run: python -m build --sdist --wheel . -o dist
      - name: publish to PyPi
        uses: pypa/gh-action-pypi-publish@master
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.pypi_password }}