name: Release

on:
  release:
    types: [published]

jobs:
  release-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install node
      uses: actions/setup-node@v3
      with:
       node-version: 16
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install jupyterlab
    - name: Build the extension
      run: |
        jlpm
 
        pip install build
        python -m build
        pip uninstall -y "jupyterlab_theme_KULeuven" jupyterlab
        
    - name: Upload extension packages
      uses: actions/upload-artifact@v3
      with:
        name: extension-artifacts
        path: dist/jupyterlab_theme_KULeuven*
        if-no-files-found: error
 
    - name: Publish to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_JANGENOE }}
        
    